Sitronnier\SmBoxBundle\Entity\Day:
  type: entity
  repositoryClass: Sitronnier\SmBoxBundle\Entity\DayRepository
  table: null
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    nb_hours:
      type: float
    nb_business_value:
      type: float
    nb_story_points:
      type: float
    date:
      type: date
    visible:
      type: boolean
      nullable: true
    nb_hours_estimate:
      type: float
      nullable: true
  manyToOne:
    sprint:
      targetEntity: Sprint 
  lifecycleCallbacks: {  }
