Sitronnier\SmBoxBundle\Entity\Sprint:
  type: entity
  repositoryClass: Sitronnier\SmBoxBundle\Entity\SprintRepository
  table: null
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    index:
      type: integer
    story_points:
      type: float
    business_value:
      type: float
    man_days:
      type: float
    status:
      type: string
    start_date:
      type: date
      nullable: true
    end_date:
      type: date
      nullable: true
  manyToOne:
    project:
      targetEntity: Project 
  oneToMany:
    days:
      targetEntity: Day
      mappedBy: sprint
      cascade: [ 'remove', 'persist' ]
  lifecycleCallbacks: {  }
