smbox_stats_sprint_data:
    pattern:  /sprint/{sprint}
    defaults: { _controller: SitronnierSmBoxBundle:Stats:sprintData }
    options:
        expose: true

smbox_stats_update_day:
    pattern:  /day/update
    defaults: { _controller: SitronnierSmBoxBundle:Stats:updateDay }
    options:
        expose: true
    requirements:
        _method:  POST

smbox_stats_delete_day:
    pattern:  /day/delete
    defaults: { _controller: SitronnierSmBoxBundle:Stats:deleteDay }
    options:
        expose: true
    requirements:
        _method:  POST

