<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120329215755 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("CREATE SEQUENCE MyUser_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE Project_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE Sprint_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE Day_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE TABLE MyUser (id INT NOT NULL, username VARCHAR(255) NOT NULL, username_canonical VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, email_canonical VARCHAR(255) NOT NULL, enabled BOOLEAN NOT NULL, salt VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, last_login TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, locked BOOLEAN NOT NULL, expired BOOLEAN NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, confirmation_token VARCHAR(255) DEFAULT NULL, password_requested_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, roles TEXT NOT NULL, credentials_expired BOOLEAN NOT NULL, credentials_expire_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))");
        $this->addSql("CREATE UNIQUE INDEX UNIQ_FA239CC492FC23A8 ON MyUser (username_canonical)");
        $this->addSql("CREATE UNIQUE INDEX UNIQ_FA239CC4A0D96FBF ON MyUser (email_canonical)");
        $this->addSql("CREATE TABLE Project (id INT NOT NULL, owner_id INT DEFAULT NULL, title VARCHAR(255) NOT NULL, zebra_url VARCHAR(255) DEFAULT NULL, jira_url VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))");
        $this->addSql("CREATE INDEX IDX_E00EE9727E3C61F9 ON Project (owner_id)");
        $this->addSql("CREATE TABLE Sprint (id INT NOT NULL, project_id INT DEFAULT NULL, index INT NOT NULL, story_points DOUBLE PRECISION NOT NULL, business_value DOUBLE PRECISION NOT NULL, man_days DOUBLE PRECISION NOT NULL, status VARCHAR(255) NOT NULL, PRIMARY KEY(id))");
        $this->addSql("CREATE INDEX IDX_E82C5081166D1F9C ON Sprint (project_id)");
        $this->addSql("CREATE TABLE Day (id INT NOT NULL, sprint_id INT DEFAULT NULL, nb_hours DOUBLE PRECISION NOT NULL, nb_business_value DOUBLE PRECISION NOT NULL, nb_story_points DOUBLE PRECISION NOT NULL, date DATE NOT NULL, PRIMARY KEY(id))");
        $this->addSql("CREATE INDEX IDX_DDED6F708C24077B ON Day (sprint_id)");
        $this->addSql("ALTER TABLE Project ADD CONSTRAINT FK_E00EE9727E3C61F9 FOREIGN KEY (owner_id) REFERENCES MyUser(id) NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("ALTER TABLE Sprint ADD CONSTRAINT FK_E82C5081166D1F9C FOREIGN KEY (project_id) REFERENCES Project(id) NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("ALTER TABLE Day ADD CONSTRAINT FK_DDED6F708C24077B FOREIGN KEY (sprint_id) REFERENCES Sprint(id) NOT DEFERRABLE INITIALLY IMMEDIATE");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("ALTER TABLE Project DROP CONSTRAINT FK_E00EE9727E3C61F9");
        $this->addSql("ALTER TABLE Sprint DROP CONSTRAINT FK_E82C5081166D1F9C");
        $this->addSql("ALTER TABLE Day DROP CONSTRAINT FK_DDED6F708C24077B");
        $this->addSql("DROP SEQUENCE MyUser_id_seq");
        $this->addSql("DROP SEQUENCE Project_id_seq");
        $this->addSql("DROP SEQUENCE Sprint_id_seq");
        $this->addSql("DROP SEQUENCE Day_id_seq");
        $this->addSql("DROP TABLE MyUser");
        $this->addSql("DROP TABLE Project");
        $this->addSql("DROP TABLE Sprint");
        $this->addSql("DROP TABLE Day");
    }
}
