<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120404220553 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("ALTER TABLE sprint ADD start_date DATE DEFAULT NULL");
        $this->addSql("ALTER TABLE sprint ADD end_date DATE DEFAULT NULL");
        $this->addSql("ALTER TABLE day ADD visible BOOLEAN DEFAULT True");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("ALTER TABLE Sprint DROP start_date");
        $this->addSql("ALTER TABLE Sprint DROP end_date");
        $this->addSql("ALTER TABLE Day DROP visible");
    }
}
