parameters:
#    sitronnier_sm_box.example.class: Sitronnier\SmBoxBundle\Example

services:
#    sitronnier_sm_box.example:
#        class: %sitronnier_sm_box.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
